In [4]:
#ad22df9b3d3f927ac2cd29f832c099b3

In [ ]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(open('flipkart.html','r',encoding='utf-8'))
print(soup.prettify())

In [ ]:

Line_tag = soup.find_all('div',class_='KzDlHZ')
Rate_tag = soup.find_all('div',class_='XQDdHH')
Price_tag = soup.find_all('div',class_='Nx9bqj _4b5DiR')

In [ ]:
Names=[]
colors=[]
ROMs=[]
for i in Line_tag:
    Names.append(i.text.strip().split(" (")[0])
    colors.append(i.text.strip().split(" (")[1].split(",")[0])
    ROMs.append(i.text.strip().split(" (")[1].split(", ")[1].split()[0])
print(Names)
print(colors)
print(ROMs)

In [ ]:
Ram_tag_box = soup.find_all('ul',class_='G4BRas')
Rams = []
for i in Ram_tag_box:
    Rams.append(i.find('li').text.strip().split('|')[0].split(' GB RAM')[0])
    
ram_1=[]    
ram=soup.find_all('li',class_='J+igdf')   
# sir 
for i in ram:
    if "RAM" in i.text:
        ram_1.append(i.text.split('|')[0][:-4])

print(Rams)
print(ram_1)

In [ ]:
rate=soup.find_all('div',class_='_5OesEi')
rate
Rates=[]
for i in rate:
    Rates.append(i.find('div',class_='XQDdHH').text)
print(Rates)
print(len(Rates))

In [ ]:
Prices=[]
price=soup.find_all('div',class_='Nx9bqi _4b5DiR')
for i in Price_tag:
    Prices.append(i.text.strip())
print(Prices)

In [ ]:
import pandas as pd
df=pd.DataFrame({'Name':Names,'Color':colors,'ROM':ROMs,'Rating':Rates,'Price':Prices})
df

In [ ]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(open('Popular_Quotes.html','r',encoding='utf-8'))
print(soup.prettify())

In [ ]:
line=[]
name=[]
lines=soup.find_all('div',class_="quoteText")
lines
for i in lines:
     line.append(i.text.strip().split('\n')[0].strip())
     name.append(i.text.strip().split('\n')[-1].strip())
print(line)
print(name)

In [ ]:
like=soup.find_all('a',class_='smallText')
likes=[]
liked=[]
for i in like:
    likes.append(i.text[:-6])
for i in likes:
    if i >'75000':
        liked.append(i)
print(likes)                    
print(len(liked))        
print(likes)

In [ ]:
import pandas as pd
df=pd.DataFrame({'Name':name,'Lines':line,'Like':likes})
df

# API
ad22df9b3d3f927ac2cd29f832c099b3

In [5]:
API_key='ad22df9b3d3f927ac2cd29f832c099b3'

In [6]:
import requests,json
def get_coordinates():
    api_key='ad22df9b3d3f927ac2cd29f832c099b3'
    city=input('Enter City Name')
    #request_url=f"http://api.openweathermap.org/geo/1.0/direct?q={city}&appid={api_key}"
    request_url='http://api.openweathermap.org/geo/1.0/direct?q='+city+'&appid='+api_key
    response=requests.get(request_url)
    coordinates=response.json()
    print(json.dumps(coordinates,indent=5))
    lattitude=coordinates[0]['lat']
    longitude=coordinates[0]['lon']
    return lattitude,longitude,city
lat,lon,city=get_coordinates()        
print(city,"Lattitude & Longitude")
print("- - - - - - - - - - - - - - - ")
print("Lattitude:",lat)
print("Longitude:",lon)

Enter City Name Ahmedabad

[
     {
          "name": "Ahmedabad",
          "local_names": {
               "mr": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "ur": "\u0627\u062d\u0645\u062f \u0622\u0628\u0627\u062f",
               "zh": "\u827e\u54c8\u8fc8\u8fbe\u5df4\u5fb7",
               "de": "Ahmedabad",
               "bn": "\u0986\u09b9\u09ae\u09c7\u09a6\u09be\u09ac\u09be\u09a6",
               "hi": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "en": "Ahmedabad",
               "feature_name": "Ahmedabad",
               "kn": "\u0c85\u0cb9\u0ccd\u0cae\u0ca6\u0cbe\u0cac\u0cbe\u0ca6\u0ccd",
               "pa": "\u0a05\u0a39\u0a3f\u0a2e\u0a26\u0a3e\u0a2c\u0a3e\u0a26",
               "gu": "\u0a85\u0aae\u0aa6\u0abe\u0ab5\u0abe\u0aa6",
               "ru": "\u0410\u0445\u043c\u0430\u0434\u0430\u0431\u0430\u0434",
               "tt": "\u04d8\u0445\u043c\u04d9\u0442\u0430\u0431\u0430\u0434",
               "ar": "\u0623\u062d\u0645\u062f \u0622\u0628\u0627\u062f",
               "cs": "Ahmad\u00e1b\u00e1d",
               "ta": "\u0b85\u0b95\u0bae\u0ba4\u0bbe\u0baa\u0bbe\u0ba4\u0bcd",
               "oc": "Ahmadabad",
               "ml": "\u0d05\u0d39\u0d2e\u0d4d\u0d2e\u0d26\u0d3e\u0d2c\u0d3e\u0d26\u0d4d",
               "ne": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "uk": "\u0410\u0445\u043c\u0435\u0434\u0430\u0431\u0430\u0434",
               "he": "\u05d0\u05d7\u05de\u05d3\u05d0\u05d1\u05d0\u05d3",
               "ja": "\u30a2\u30d5\u30de\u30c0\u30fc\u30d0\u30fc\u30c9",
               "or": "\u0b05\u0b39\u0b2e\u0b26\u0b3e\u0b2c\u0b3e\u0b26",
               "pl": "Ahmadabad",
               "ascii": "Ahmedabad",
               "eo": "Ahmadabado",
               "te": "\u0c05\u0c39\u0c4d\u0c2e\u0c26\u0c3e\u0c2c\u0c3e\u0c26\u0c4d"
          },
          "lat": 23.0215374,
          "lon": 72.5800568,
          "country": "IN",
          "state": "Gujarat"
     }
]
Ahmedabad Lattitude & Longitude
- - - - - - - - - - - - - - -
Lattitude: 23.0215374
Longitude: 72.5800568

In [14]:
import requests,json
def current_weather_data():
    api_key='ad22df9b3d3f927ac2cd29f832c099b3'
    request_url=f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={api_key}"
    response=requests.get(request_url)
    weather_data=response.json()
    print(json.dumps(weather_data,indent=5))
    return weather_data
weather_data=current_weather_data()        
description=weather_data["weather"][0]["description"]
temperture=weather_data['main']['temp']
pressure=weather_data['main']['pressure']
humidity=weather_data['main']['humidity']
wind_speed=weather_data['wind']['speed']
visibility=weather_data['visibility']
print(description)
print(temperture)
print(pressure)
print(humidity)
print(wind_speed)
print(visibility)

{
     "coord": {
          "lon": 72.5801,
          "lat": 23.0215
     },
     "weather": [
          {
               "id": 721,
               "main": "Haze",
               "description": "haze",
               "icon": "50d"
          }
     ],
     "base": "stations",
     "main": {
          "temp": 303.19,
          "feels_like": 305.66,
          "temp_min": 303.19,
          "temp_max": 303.19,
          "pressure": 1010,
          "humidity": 58,
          "sea_level": 1010,
          "grnd_level": 1004
     },
     "visibility": 4000,
     "wind": {
          "speed": 3.09,
          "deg": 240
     },
     "clouds": {
          "all": 0
     },
     "dt": 1779680999,
     "sys": {
          "type": 1,
          "id": 9049,
          "country": "IN",
          "sunrise": 1779668728,
          "sunset": 1779716881
     },
     "timezone": 19800,
     "id": 1279233,
     "name": "Ahmedabad",
     "cod": 200
}
haze
303.19
1010
58
3.09
4000

In [29]:
import requests,json
def Air_polution():
    api_key='ad22df9b3d3f927ac2cd29f832c099b3'
    request_url=f"http://api.openweathermap.org/data/2.5/air_pollution?lat={lat}&lon={lon}&appid={api_key}"
    response=requests.get(request_url)
    weather_data=response.json()
    print(json.dumps(weather_data,indent=5))
    return weather_data
weather_data=Air_polution()
aqi=weather_data["list"][0]["main"]["aqi"]
if(aqi==1):
    print("Good")
elif(aqi==2):    
    print("Fair")
elif(aqi==3):    
    print("Moderate")
elif(aqi==4):    
    print("Poor")
elif(aqi==5):    
    print("Very Poor")

{
     "coord": {
          "lon": 72.5801,
          "lat": 23.0215
     },
     "list": [
          {
               "main": {
                    "aqi": 1
               },
               "components": {
                    "co": 103.27,
                    "no": 0.52,
                    "no2": 1.52,
                    "o3": 39.49,
                    "so2": 2.24,
                    "pm2_5": 4.89,
                    "pm10": 14.12,
                    "nh3": 1.14
               },
               "dt": 1779682295
          }
     ]
}
Good

In [28]:
quality={1:"Good",2:"Fair",3:"Moderate",4:"Poor",5:"Very Poor"}
print(quality[aqi])

Good

In [55]:
import requests,json
def forcast():
    api_key='ad22df9b3d3f927ac2cd29f832c099b3'
    request_url=f"https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={api_key}"
    response=requests.get(request_url)
    weather_data=response.json()
    print(json.dumps(weather_data,indent=5))
    return weather_data
weather_data=forcast()
temperture=[]
pressure=[]
humidity=[]
wind_speed=[]
visibility=[]
date=[]
time=[]
des=[]
#print(lis)
for i in weather_data['list']:
        temperture.append(i['main']['temp'])
        pressure.append(i['main']['pressure'])
        humidity.append(i['main']['humidity'])
        wind_speed.append(i['wind']['speed'])
        visibility.append(i['visibility'])
        des.append(i['weather'][0]["description"])
        date.append(i["dt_txt"].split(" ")[0])  
        time.append(i["dt_txt"].split(" ")[1])  
print(temperture)
print(pressure)
print(humidity)
print(wind_speed)
print(visibility)
print(date)    
print(time)
print(des)

{
     "cod": "200",
     "message": 0,
     "cnt": 40,
     "list": [
          {
               "dt": 1779688800,
               "main": {
                    "temp": 304.19,
                    "feels_like": 306.03,
                    "temp_min": 304.19,
                    "temp_max": 311.64,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1003,
                    "humidity": 51,
                    "temp_kf": -7.45
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.18,
                    "deg": 258,
                    "gust": 6.6
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-25 06:00:00"
          },
          {
               "dt": 1779699600,
               "main": {
                    "temp": 308.08,
                    "feels_like": 309.66,
                    "temp_min": 308.08,
                    "temp_max": 315.86,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 999,
                    "humidity": 38,
                    "temp_kf": -7.78
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.76,
                    "deg": 252,
                    "gust": 6.1
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-25 09:00:00"
          },
          {
               "dt": 1779710400,
               "main": {
                    "temp": 311.94,
                    "feels_like": 312.27,
                    "temp_min": 311.94,
                    "temp_max": 315.82,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 998,
                    "humidity": 25,
                    "temp_kf": -3.88
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.37,
                    "deg": 273,
                    "gust": 6.48
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-25 12:00:00"
          },
          {
               "dt": 1779721200,
               "main": {
                    "temp": 309.51,
                    "feels_like": 308.69,
                    "temp_min": 309.51,
                    "temp_max": 309.51,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 25,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.08,
                    "deg": 240,
                    "gust": 8.2
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-25 15:00:00"
          },
          {
               "dt": 1779732000,
               "main": {
                    "temp": 305.4,
                    "feels_like": 305.79,
                    "temp_min": 305.4,
                    "temp_max": 305.4,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1001,
                    "humidity": 40,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 3.7,
                    "deg": 268,
                    "gust": 7.36
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-25 18:00:00"
          },
          {
               "dt": 1779742800,
               "main": {
                    "temp": 303.02,
                    "feels_like": 304.16,
                    "temp_min": 303.02,
                    "temp_max": 303.02,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1001,
                    "humidity": 51,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 3.88,
                    "deg": 258,
                    "gust": 7.64
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-25 21:00:00"
          },
          {
               "dt": 1779753600,
               "main": {
                    "temp": 301.87,
                    "feels_like": 304.15,
                    "temp_min": 301.87,
                    "temp_max": 301.87,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1001,
                    "humidity": 63,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.36,
                    "deg": 269,
                    "gust": 9.01
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-26 00:00:00"
          },
          {
               "dt": 1779764400,
               "main": {
                    "temp": 304.94,
                    "feels_like": 307.13,
                    "temp_min": 304.94,
                    "temp_max": 304.94,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1003,
                    "humidity": 50,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.19,
                    "deg": 259,
                    "gust": 7.22
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-26 03:00:00"
          },
          {
               "dt": 1779775200,
               "main": {
                    "temp": 311.96,
                    "feels_like": 312.3,
                    "temp_min": 311.96,
                    "temp_max": 311.96,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1001,
                    "humidity": 25,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.25,
                    "deg": 252,
                    "gust": 6.45
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-26 06:00:00"
          },
          {
               "dt": 1779786000,
               "main": {
                    "temp": 316.34,
                    "feels_like": 315.16,
                    "temp_min": 316.34,
                    "temp_max": 316.34,
                    "pressure": 1003,
                    "sea_level": 1003,
                    "grnd_level": 998,
                    "humidity": 15,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.99,
                    "deg": 249,
                    "gust": 6.49
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-26 09:00:00"
          },
          {
               "dt": 1779796800,
               "main": {
                    "temp": 316.31,
                    "feels_like": 315.12,
                    "temp_min": 316.31,
                    "temp_max": 316.31,
                    "pressure": 1002,
                    "sea_level": 1002,
                    "grnd_level": 997,
                    "humidity": 15,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.96,
                    "deg": 274,
                    "gust": 6.74
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-26 12:00:00"
          },
          {
               "dt": 1779807600,
               "main": {
                    "temp": 308.95,
                    "feels_like": 310.62,
                    "temp_min": 308.95,
                    "temp_max": 308.95,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 36,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.57,
                    "deg": 230,
                    "gust": 8.26
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-26 15:00:00"
          },
          {
               "dt": 1779818400,
               "main": {
                    "temp": 305.34,
                    "feels_like": 306.7,
                    "temp_min": 305.34,
                    "temp_max": 305.34,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1001,
                    "humidity": 45,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.34,
                    "deg": 262,
                    "gust": 8.02
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-26 18:00:00"
          },
          {
               "dt": 1779829200,
               "main": {
                    "temp": 302.99,
                    "feels_like": 306.07,
                    "temp_min": 302.99,
                    "temp_max": 302.99,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 62,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.04,
                    "deg": 254,
                    "gust": 7.46
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-26 21:00:00"
          },
          {
               "dt": 1779840000,
               "main": {
                    "temp": 301.87,
                    "feels_like": 305.11,
                    "temp_min": 301.87,
                    "temp_max": 301.87,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1002,
                    "humidity": 69,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.15,
                    "deg": 279,
                    "gust": 7.87
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-27 00:00:00"
          },
          {
               "dt": 1779850800,
               "main": {
                    "temp": 304.67,
                    "feels_like": 307.82,
                    "temp_min": 304.67,
                    "temp_max": 304.67,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1003,
                    "humidity": 55,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.22,
                    "deg": 252,
                    "gust": 6.72
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-27 03:00:00"
          },
          {
               "dt": 1779861600,
               "main": {
                    "temp": 311.99,
                    "feels_like": 312.35,
                    "temp_min": 311.99,
                    "temp_max": 311.99,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1002,
                    "humidity": 25,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.79,
                    "deg": 250,
                    "gust": 5.74
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-27 06:00:00"
          },
          {
               "dt": 1779872400,
               "main": {
                    "temp": 316.46,
                    "feels_like": 315.31,
                    "temp_min": 316.46,
                    "temp_max": 316.46,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 999,
                    "humidity": 15,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.31,
                    "deg": 254,
                    "gust": 5.6
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-27 09:00:00"
          },
          {
               "dt": 1779883200,
               "main": {

In [57]:
import pandas as pd
df=pd.DataFrame({
    "Temperture":temperture,
    "Pressure":pressure,
    "Hudidity":humidity,
    "Wind_speed":wind_speed,
    "Description":des,
    "Visibility":visibility,
    "Date":date,
    "Time":time})
df

,Temperture,Pressure,Hudidity,Wind_speed,Description,Visibility,Date,Time
0,304.19,1008,51,5.18,clear sky,10000,2026-05-25,06:00:00
1,308.08,1007,38,5.76,clear sky,10000,2026-05-25,09:00:00
2,311.94,1005,25,6.37,clear sky,10000,2026-05-25,12:00:00
3,309.51,1005,25,5.08,clear sky,10000,2026-05-25,15:00:00
4,305.40,1007,40,3.70,clear sky,10000,2026-05-25,18:00:00
5,303.02,1006,51,3.88,clear sky,10000,2026-05-25,21:00:00
6,301.87,1007,63,4.36,clear sky,10000,2026-05-26,00:00:00
7,304.94,1008,50,5.19,clear sky,10000,2026-05-26,03:00:00
8,311.96,1007,25,5.25,clear sky,10000,2026-05-26,06:00:00
9,316.34,1003,15,5.99,clear sky,10000,2026-05-26,09:00:00
10,316.31,1002,15,6.96,clear sky,10000,2026-05-26,12:00:00
11,308.95,1005,36,5.57,clear sky,10000,2026-05-26,15:00:00
12,305.34,1006,45,4.34,clear sky,10000,2026-05-26,18:00:00
13,302.99,1005,62,4.04,clear sky,10000,2026-05-26,21:00:00
14,301.87,1007,69,4.15,clear sky,10000,2026-05-27,00:00:00
15,304.67,1008,55,5.22,clear sky,10000,2026-05-27,03:00:00
16,311.99,1007,25,4.79,clear sky,10000,2026-05-27,06:00:00
17,316.46,1004,15,5.31,clear sky,10000,2026-05-27,09:00:00
18,317.04,1002,14,5.54,clear sky,10000,2026-05-27,12:00:00
19,306.65,1006,53,5.60,clear sky,10000,2026-05-27,15:00:00
20,305.69,1007,49,3.62,clear sky,10000,2026-05-27,18:00:00
21,303.27,1005,67,5.67,clear sky,10000,2026-05-27,21:00:00
22,302.89,1007,63,5.01,clear sky,10000,2026-05-28,00:00:00
23,305.01,1008,54,5.05,clear sky,10000,2026-05-28,03:00:00
24,312.35,1007,25,5.65,clear sky,10000,2026-05-28,06:00:00
25,317.34,1003,14,6.14,clear sky,10000,2026-05-28,09:00:00
26,316.61,1002,17,6.77,clear sky,10000,2026-05-28,12:00:00
27,306.26,1005,56,5.21,clear sky,10000,2026-05-28,15:00:00
28,305.46,1006,50,4.24,clear sky,10000,2026-05-28,18:00:00
29,304.52,1005,57,5.69,clear sky,10000,2026-05-28,21:00:00
30,302.61,1006,67,4.92,clear sky,10000,2026-05-29,00:00:00
31,305.24,1007,54,6.45,clear sky,10000,2026-05-29,03:00:00
32,312.44,1006,26,6.69,clear sky,10000,2026-05-29,06:00:00
33,316.86,1002,17,7.58,clear sky,10000,2026-05-29,09:00:00
34,316.73,1001,18,7.37,clear sky,10000,2026-05-29,12:00:00
35,308.63,1003,39,5.60,clear sky,10000,2026-05-29,15:00:00
36,305.06,1003,54,5.08,clear sky,10000,2026-05-29,18:00:00
37,304.06,1003,58,6.66,clear sky,10000,2026-05-29,21:00:00
38,302.28,1004,70,6.68,clear sky,10000,2026-05-30,00:00:00
39,305.12,1005,56,7.79,scattered clouds,10000,2026-05-30,03:00:00

In [67]:
data={'Date_Time':[],'Temperature':[],'Pressure':[],'Humidity':[],'Wind Speed':[],'Visibility':[],'Description':[]}
for i in weather_data['list']:
        data['Date_Time'].append(i['dt_txt'])
        data['Temperature'].append(i['main']['temp'])
        data['Pressure'].append(i['main']['pressure'])
        data['Humidity'].append(i['main']['humidity'])
        data['Description'].append(i['weather'][0]['description'])
        data['Wind Speed'].append(i['wind']['speed'])
        data['Visibility'].append(i['visibility'])
df=pd.DataFrame(data)
df

,Date_Time,Temperature,Pressure,Humidity,Wind Speed,Visibility,Description
0,2026-05-25 06:00:00,304.19,1008,51,5.18,10000,clear sky
1,2026-05-25 09:00:00,308.08,1007,38,5.76,10000,clear sky
2,2026-05-25 12:00:00,311.94,1005,25,6.37,10000,clear sky
3,2026-05-25 15:00:00,309.51,1005,25,5.08,10000,clear sky
4,2026-05-25 18:00:00,305.40,1007,40,3.70,10000,clear sky
5,2026-05-25 21:00:00,303.02,1006,51,3.88,10000,clear sky
6,2026-05-26 00:00:00,301.87,1007,63,4.36,10000,clear sky
7,2026-05-26 03:00:00,304.94,1008,50,5.19,10000,clear sky
8,2026-05-26 06:00:00,311.96,1007,25,5.25,10000,clear sky
9,2026-05-26 09:00:00,316.34,1003,15,5.99,10000,clear sky
10,2026-05-26 12:00:00,316.31,1002,15,6.96,10000,clear sky
11,2026-05-26 15:00:00,308.95,1005,36,5.57,10000,clear sky
12,2026-05-26 18:00:00,305.34,1006,45,4.34,10000,clear sky
13,2026-05-26 21:00:00,302.99,1005,62,4.04,10000,clear sky
14,2026-05-27 00:00:00,301.87,1007,69,4.15,10000,clear sky
15,2026-05-27 03:00:00,304.67,1008,55,5.22,10000,clear sky
16,2026-05-27 06:00:00,311.99,1007,25,4.79,10000,clear sky
17,2026-05-27 09:00:00,316.46,1004,15,5.31,10000,clear sky
18,2026-05-27 12:00:00,317.04,1002,14,5.54,10000,clear sky
19,2026-05-27 15:00:00,306.65,1006,53,5.60,10000,clear sky
20,2026-05-27 18:00:00,305.69,1007,49,3.62,10000,clear sky
21,2026-05-27 21:00:00,303.27,1005,67,5.67,10000,clear sky
22,2026-05-28 00:00:00,302.89,1007,63,5.01,10000,clear sky
23,2026-05-28 03:00:00,305.01,1008,54,5.05,10000,clear sky
24,2026-05-28 06:00:00,312.35,1007,25,5.65,10000,clear sky
25,2026-05-28 09:00:00,317.34,1003,14,6.14,10000,clear sky
26,2026-05-28 12:00:00,316.61,1002,17,6.77,10000,clear sky
27,2026-05-28 15:00:00,306.26,1005,56,5.21,10000,clear sky
28,2026-05-28 18:00:00,305.46,1006,50,4.24,10000,clear sky
29,2026-05-28 21:00:00,304.52,1005,57,5.69,10000,clear sky
30,2026-05-29 00:00:00,302.61,1006,67,4.92,10000,clear sky
31,2026-05-29 03:00:00,305.24,1007,54,6.45,10000,clear sky
32,2026-05-29 06:00:00,312.44,1006,26,6.69,10000,clear sky
33,2026-05-29 09:00:00,316.86,1002,17,7.58,10000,clear sky
34,2026-05-29 12:00:00,316.73,1001,18,7.37,10000,clear sky
35,2026-05-29 15:00:00,308.63,1003,39,5.60,10000,clear sky
36,2026-05-29 18:00:00,305.06,1003,54,5.08,10000,clear sky
37,2026-05-29 21:00:00,304.06,1003,58,6.66,10000,clear sky
38,2026-05-30 00:00:00,302.28,1004,70,6.68,10000,clear sky
39,2026-05-30 03:00:00,305.12,1005,56,7.79,10000,scattered clouds

In [ ]:
Nasa_api:'2ic071DDGifmxcGkqruro7yfXfIwofuxOgIhqMeJ'

In [69]:
import requests
import pandas as pd 
url = "https://api.nasa.gov/planetary/apod"
API="2ic071DDGifmxcGkqruro7yfXfIwofuxOgIhqMeJ"
responses = requests.get(url,params={'api_key':API,'count':10})
data = responses.json()
print(data)

[{'date': '1996-05-27', 'explanation': "What do aurora look like from space? The POLAR spacecraft answered this by photographing an auroral oval surrounding the north pole of the Earth, causing displays on both the night and day side. The auroral sub-storm, pictured in false-color above, developed within 15 minutes and may have lasted as long as on hour.  Aurora are caused by charged particles streaming away from the Sun and towards the Earth. As the particles fall to Earth, they spiral along magnetic field lines and cause colorful radiation. The UVI experiment onboard the POLAR spacecraft is equipped with special filters that allow it to see aurora in a band of ultraviolet light where sunlight is relatively dim.  The more red the emission depicted in the above photo, the more intense the radiation. Earth's continents have been drawn in for clarity", 'hdurl': 'https://apod.nasa.gov/apod/image/aurora_polar_big.gif', 'media_type': 'image', 'service_version': 'v1', 'title': 'Aurora Crown the Earth', 'url': 'https://apod.nasa.gov/apod/image/aurora_polar.gif'}, {'copyright': 'Marcella Giulia Pace', 'date': '2021-12-04', 'explanation': "In this snapshot from November 18, the Full Moon was not far from Earth's shadow. In skies over Sicily the brightest lunar phase was eclipsed by passing clouds though. The full moonlight was dimmed and momentarily diffracted by small but similar sized water droplets near the edges of the high thin clouds. The resulting iridescence shines with colors like a lunar corona. On that night, the Full Moon was also seen close to the Pleiades star cluster appearing at the lower left of the iridescent cloud bank. The stars of the Seven Sisters were soon to share the sky with a darker, reddened lunar disk.", 'hdurl': 'https://apod.nasa.gov/apod/image/2112/IridescenzaLunaPleiadi.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Iridescent by Moonlight', 'url': 'https://apod.nasa.gov/apod/image/2112/IridescenzaLunaPleiadi1024.jpg'}, {'date': '2002-09-14', 'explanation': "This x-ray image of the Moon was made by the orbiting ROSAT (Röntgensatellit) Observatory in 1990. In this digital picture, pixel brightness corresponds to x-ray intensity. Consider the image in three parts: the bright hemisphere of the x-ray moon, the darker half of the moon, and the x-ray sky background. The bright lunar hemisphere shines in x-rays because it scatters x-rays emitted by the sun. The background sky has an x-ray glow in part due to the myriad of distant, powerful active galaxies, unresolved in the ROSAT picture but recently detected in Chandra Observatory x-ray images. But why isn't the dark half of the moon completely dark? It's true that the dark lunar face is in shadow and so is shielded from direct solar x-rays. Still, the few x-ray photons which seem to come from the moon's dark half are currently thought to be caused by energetic particles in the solar wind bombarding the lunar surface.", 'hdurl': 'https://apod.nasa.gov/apod/image/0209/rosat_moon_big.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'X-Ray Moon', 'url': 'https://apod.nasa.gov/apod/image/0209/rosat_moon.jpg'}, {'date': '2007-03-07', 'explanation': "A new spacecraft is headed for the outer Solar System.  Named New Horizons, this robotic explorer passed Jupiter last week after being launched only in early 2006.  New Horizons is being pulled by Jupiter's gravity to a greater speed toward its next target: Pluto in 2015. During its encounter with Jupiter, New Horizons was able to capture new images of many Jovian moons, Jupiter's complex and ever-changing atmosphere, and Jupiter's Little Red Spot, pictured above. Formed over the past few years from several smaller storms, Jupiter's Little Red Spot survived a near miss with Jupiter's better-known Great Red Spot last year. The above image of Jupiter covers over twice the diameter of the Earth.", 'hdurl': 'https://apod.nasa.gov/apod/image/0703/jupiter_newhorizons_big.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'New Horizons Spacecraft Passes Jupiter', 'url': 'https://apod.nasa.gov/apod/image/0703/jupiter_newhorizons.jpg'}, {'date': '2006-04-05', 'explanation': "When orbiting Saturn, be sure to watch for breathtaking superpositions of moons, rings, and shadows.   One such picturesque vista was visible recently to the robot Cassini spacecraft now orbiting Saturn.   In late February, Cassini captured  Rhea, the second largest moon of Saturn, while looking up from slightly beneath Saturn's expansive ring plane.   Signature dark gaps are visible in the nearly edge-on rings.   A shadow of Saturn's F ring cuts across the cratered ice-moon.   Cassini is scheduled to continue sending back images from the orbit of Saturn until at least 2008.", 'hdurl': 'https://apod.nasa.gov/apod/image/0604/rhearings_cassini_big.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': "Slightly Beneath Saturn's Ring Plane", 'url': 'https://apod.nasa.gov/apod/image/0604/rhearings_cassini.jpg'}, {'copyright': 'E. Winfree, \nK. Fleischer, A. Barr \net al. \n(Caltech)', 'date': '2002-04-30', 'explanation': 'Is this image worth a thousand words?  According to the Holographic Principle, the most information you can get from this image is about 3 x 1065 bits for a normal sized computer monitor.  The Holographic Principle, yet unproven, states that there is a maximum amount of information content held by regions adjacent to any surface.  Therefore, counter-intuitively, the information content inside a room depends not on the volume of the room but on the area of the bounding walls.  The principle derives from the idea that the Planck length, the length scale where quantum mechanics begins to dominate classical gravity, is one side of an area that can hold only about one bit of information.  The limit was first postulated by physicist Gerard \'t Hooft in 1993.  It can arise from generalizations from seemingly distant speculation that the information held by a black hole is determined not by its enclosed volume but by the surface area of its event horizon.  The term "holographic" arises from a hologram analogy where three-dimension images are created by projecting light though a flat screen.  Beware, other people looking at the above image may not claim to see 3 x 1065 bits -- they might claim to see a teapot.', 'hdurl': 'https://apod.nasa.gov/apod/image/0204/teapotsirds_winfree_big.gif', 'media_type': 'image', 'service_version': 'v1', 'title': 'The Holographic Principle', 'url': 'https://apod.nasa.gov/apod/image/0204/teapotsirds_winfree.gif'}, {'copyright': 'Mike Cohea', 'date': '2021-09-23', 'explanation': "Famed in festival, story, and song the best known full moon is the Harvest Moon. For northern hemisphere dwellers that's a traditional name of the full moon nearest the September equinox. Seen from Saunderstown, Rhode Island, planet Earth, this Harvest Moon left a broad streak of warm hues as it rose through a twilight sky over the Newport Bridge. On September 20 its trail was captured in a single 22 minute exposure using a dense filter and a digital camera. Only two days later the September equinox marked a change of season and the beginning of autumn in the north. In fact, recognizing a season as the time between solstice and equinox, this Harvest Moon was the fourth full moon of the season, coming just before the astronomical end of northern summer.", 'hdurl': 'https://apod.nasa.gov/apod/image/2109/Cohea_APOD_HarvestMoon.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Harvest Moon Trail', 'url': 'https://apod.nasa.gov/apod/image/2109/Cohea_APOD_HarvestMoon1067.jpg'}, {'date': '2017-04-01', 'explanation': "Just now, before you hit the button, two future universes are possible.  After pressing the button, though, you will live in only one.  A real-web version of the famous Schr�dinger's cat experiment, clicking the red button in the featured astronaut image should transform that image into a picture of the same astronaut holding one of two cats -- one living, or one dead.  The timing of your click, combined with the wiring of your brain and the millisecond timing of your device, will all conspire together to create a result dominated, potentially, by the randomness of quantum mechanics.  Some believe that your personally-initiated quantum decision will split the universe in two, and that both the live-cat and dead-cat universes exist in separate parts of a larger multiverse. Others believe that the result of your click will collapse the two possible universes into one -- in a way that could not have been predicted beforehand.  Yet others believe that the universe is classically deterministic, so that by pressing the button you did not really split the universe, but just carried out an action predestined since time began.   We at APOD believe that however foolish you may feel clicking the red button, and regardless of the outcome,  you should have a happy April Fool's Day.", 'hdurl': 'https://apod.nasa.gov/apod/image/1704/SatelliteSale_NASA_960_split3.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Split the Universe', 'url': 'https://apod.nasa.gov/apod/image/1704/SatelliteSale_NASA_960_split3.jpg'}, {'copyright': 'Rogelio Bernal\nAndreo', 'date': '2017-06-24', 'explanation': "Top to bottom, this colorful and broad telescopic mosaic links Markarian's Chain of galaxies across the core of the Virgo Cluster to dusty spiral galaxy Messier 64. Galaxies are scattered through the field of view that spans some 20 full moons across a gorgeous night sky. The cosmic frame is also filled with foreground stars from constellations Virgo and the well-groomed Coma Berenices, and faint, dusty nebulae drifting above the plane of the Milky Way. Look carefully for Markarian's eyes. The famous pair of interacting galaxies is near the top, not far from M87, the Virgo cluster's giant elliptical galaxy. At the bottom, you can stare down Messier 64, also known as the Black Eye Galaxy. The Virgo Cluster is the closest large galaxy cluster to our own local galaxy group. Virgo Cluster galaxies are about 50 million light-years distant, but M64 lies a mere 17 million light-years away.", 'hdurl': 'https://apod.nasa.gov/apod/image/1706/RBA_DS_Mk2M64_2048V.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': "Markarian's Chain to Messier 64", 'url': 'https://apod.nasa.gov/apod/image/1706/RBA_DS_Mk2M64_1024V0.jpg'}, {'date': '2006-11-05', 'explanation': "Galaxies don't normally look like this.  NGC 6745 actually shows the results of two galaxies that have been colliding for only hundreds of millions of years.  Just off the above photograph to the lower right is the smaller galaxy, moving away.  The larger galaxy, pictured above, used to be a spiral galaxy but now is damaged and appears peculiar.  Gravity has distorted the shapes of the galaxies.  Although it is likely that no stars in the two galaxies directly collided, the gas, dust, and ambient magnetic fields do interact directly. In fact, a knot of gas pulled off the larger galaxy on the lower right has now begun to form stars.  NGC 6745 spans about 80 thousand light-years across and is located about 200 million light-years away.", 'hdurl': 'https://apod.nasa.gov/apod/image/0611/ngc6745_hst_big.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'A Galaxy Collision in NGC 6745', 'url': 'https://apod.nasa.gov/apod/image/0611/ngc6745_hst.jpg'}]

In [1]:
import requests
import json
url="https://jsonplaceholder.typicode.com/posts/1"
response=requests.get(url)
print(response.status_code)
data=response.json()
print(json.dumps(data,indent=5))

200
{
     "userId": 1,
     "id": 1,
     "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
     "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

In [2]:
print(response.json())

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [5]:
print(type(response.json()))

<class 'dict'>

In [4]:
print(response.text)

{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

In [7]:
print(type(response.text))

<class 'str'>

In [8]:
url="https://jsonplaceholder.typicode.com/posts"
response=requests.get(url)
print(response.status_code)
data=response.json()
print(json.dumps(data,indent=5))

200
[
     {
          "userId": 1,
          "id": 1,
          "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
          "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
     },
     {
          "userId": 1,
          "id": 2,
          "title": "qui est esse",
          "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"
     },
     {
          "userId": 1,
          "id": 3,
          "title": "ea molestias quasi exercitationem repellat qui ipsa sit aut",
          "body": "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut"
     },
     {
          "userId": 1,
          "id": 4,
          "title": "eum et est occaecati",
          "body": "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit"
     },
     {
          "userId": 1,
          "id": 5,
          "title": "nesciunt quas odio",
          "body": "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque"
     },
     {
          "userId": 1,
          "id": 6,
          "title": "dolorem eum magni eos aperiam quia",
          "body": "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae"
     },
     {
          "userId": 1,
          "id": 7,
          "title": "magnam facilis autem",
          "body": "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas"
     },
     {
          "userId": 1,
          "id": 8,
          "title": "dolorem dolore est ipsam",
          "body": "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae"
     },
     {
          "userId": 1,
          "id": 9,
          "title": "nesciunt iure omnis dolorem tempora et accusantium",
          "body": "consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas"
     },
     {
          "userId": 1,
          "id": 10,
          "title": "optio molestias id quia eum",
          "body": "quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error"
     },
     {
          "userId": 2,
          "id": 11,
          "title": "et ea vero quia laudantium autem",
          "body": "delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi"
     },
     {
          "userId": 2,
          "id": 12,
          "title": "in quibusdam tempore odit est dolorem",
          "body": "itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio"
     },
     {
          "userId": 2,
          "id": 13,
          "title": "dolorum ut in voluptas mollitia et saepe quo animi",
          "body": "aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam"
     },
     {
          "userId": 2,
          "id": 14,
          "title": "voluptatem eligendi optio",
          "body": "fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum"
     },
     {
          "userId": 2,
          "id": 15,
          "title": "eveniet quod temporibus",
          "body": "reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae"
     },
     {
          "userId": 2,
          "id": 16,
          "title": "sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio",
          "body": "suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta"
     },
     {
          "userId": 2,
          "id": 17,
          "title": "fugit voluptas sed molestias voluptatem provident",
          "body": "eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo"
     },
     {
          "userId": 2,
          "id": 18,
          "title": "voluptate et itaque vero tempora molestiae",
          "body": "eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam"
     },
     {
          "userId": 2,
          "id": 19,
          "title": "adipisci placeat illum aut reiciendis qui",
          "body": "illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas"
     },
     {
          "userId": 2,
          "id": 20,
          "title": "doloribus ad provident suscipit at",
          "body": "qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo"
     },
     {
          "userId": 3,
          "id": 21,
          "title": "asperiores ea ipsam voluptatibus modi minima quia sint",
          "body": "repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt"
     },
     {
          "userId": 3,
          "id": 22,
          "title": "dolor sint quo a velit explicabo quia nam",
          "body": "eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse"
     },
     {
          "userId": 3,
          "id": 23,
          "title": "maxime id vitae nihil numquam",
          "body": "veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis"
     },
     {
          "userId": 3,
          "id": 24,
          "title": "autem hic labore sunt dolores incidunt",
          "body": "enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt"
     },
     {
          "userId": 3,
          "id": 25,
          "title": "rem alias distinctio quo quis",
          "body": "ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio"
     },
     {
          "userId": 3,
          "id": 26,
          "title": "est et quae odit qui non",
          "body": "similique esse doloribus nihil accusamus\nomnis dolorem fuga consequuntur reprehenderit fugit recusandae temporibus\nperspiciatis cum ut laudantium\nomnis aut molestiae vel vero"
     },
     {
          "userId": 3,
          "id": 27,
          "title": "quasi id et eos tenetur aut quo autem",
          "body": "eum sed dolores ipsam sint possimus debitis occaecati\ndebitis qui qui et\nut placeat enim earum aut odit facilis\nconsequatur suscipit necessitatibus rerum sed inventore temporibus consequatur"
     },
     {
          "userId": 3,
          "id": 28,
          "title": "delectus ullam et corporis nulla voluptas sequi",
          "body": "non et quaerat ex quae ad maiores\nmaiores recusandae totam aut blanditiis mollitia quas illo\nut voluptatibus voluptatem\nsimilique nostrum eum"
     },
     {
          "userId": 3,
          "id": 29,
          "title": "iusto eius quod necessitatibus culpa ea",
          "body": "odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus illo dolor\neligendi repudiandae odit magni similique sed cum maiores"
     },
     {
          "userId": 3,
          "id": 30,
          "title": "a quo magni similique perferendis",
          "body": "alias dolor cumque\nimpedit blanditiis non eveniet odio maxime\nblanditiis amet eius quis tempora quia autem rem\na provident perspiciatis quia"
     },
     {
          "userId": 4,
          "id": 31,
          "title": "ullam ut quidem id aut vel consequuntur",
          "body": "debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae"
     },
     {
          "userId": 4,
          "id": 32,
          "title": "doloremque illum aliquid sunt",
          "body": "deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime"
     },
     {
          "userId": 4,
          "id": 33,
          "title": "qui explicabo molestiae dolorem",
          "body": "rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod"
     },
     {
          "userId": 4,
          "id": 34,
          "title": "magnam ut rerum iure",
          "body": "ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis"
     },
     {
          "userId": 4,
          "id": 35,
          "title": "id nihil consequatur molestias animi provident",
          "body": "nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit"
     },
     {
          "userId": 4,
          "id": 36,
          "title": "fuga nam accusamus voluptas reiciendis itaque",
          "body": "ad mollitia et omnis minus architecto odit\nvoluptas doloremque maxime aut non ipsa qui alias veniam\nblanditiis culpa aut quia nihil cumque facere et occaecati\nqui aspernatur quia eaque ut aperiam inventore"
     },
     {
          "userId": 4,
          "id": 37,
          "title": "provident vel ut sit ratione est",
          "body": "debitis et eaque non officia sed nesciunt pariatur vel\nvoluptatem iste vero et ea\nnumquam aut expedita ipsum nulla in\nvoluptates omnis consequatur aut enim officiis in quam qui"
     },
     {
          "userId": 4,
          "id": 38,
          "title": "explicabo et eos deleniti nostrum ab id repellendus",
          "body": "animi esse sit aut sit nesciunt assumenda eum voluptas\nquia voluptatibus provident quia necessitatibus ea\nrerum repudiandae quia voluptatem delectus fugit aut id quia\nratione optio eos iusto veniam iure"
     },
     {
          "userId": 4,
          "id": 39,
          "title": "eos dolorem iste accusantium est eaque quam",
          "body": "corporis rerum ducimus vel eum accusantium\nmaxime aspernatur a porro possimus iste omnis\nest in deleniti asperiores fuga aut\nvoluptas sapiente vel dolore minus voluptatem incidunt ex"
     },
     {
          "userId": 4,
          "id": 40,
          "title": "enim quo cumque",
          "body": "ut voluptatum aliquid illo tenetur nemo sequi quo facilis\nipsum rem optio mollitia quas\nvoluptatem eum voluptas qui\nunde omnis voluptatem iure quasi maxime voluptas nam"
     },
     {
          "userId": 5,
          "id": 41,
          "title": "non est facere",
          "body": "molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe"
     },
     {
          "userId": 5,
          "id": 42,
          "title": "commodi ullam sint et excepturi error explicabo praesentium voluptas",
          "body": "odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut"
     },
     {
          "userId": 5,
          "id": 43,
          "title": "eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis",
          "body": "similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis"
     },
     {
          "userId": 5,
          "id": 44,
          "title": "optio dolor molestias sit",
          "body": "temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae"
     },
     {
          "userId": 5,
          "id": 45,
          "title": "ut numquam possimus omnis eius suscipit laudantium iure",
          "body": "est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem"
     },
     {
          "userId": 5,
          "id": 46,
          "title": "aut quo modi neque nostrum ducimus",
          "body": "voluptatem quisquam iste\nvoluptatibus natus officiis facilis dolorem\nquis quas ipsam\nvel et voluptatum in aliquid"
     },
     {
          "userId": 5,
          "id": 47,
          "title": "quibusdam cumque rem aut deserunt",
          "body": "voluptatem assumenda ut qui ut cupiditate aut impedit veniam\noccaecati nemo illum voluptatem laudantium\nmolestiae beatae rerum ea iure soluta nostrum\neligendi et voluptate"
     },
     {
          "userId": 5,
          "id": 48,
          "title": "ut voluptatem illum ea doloribus itaque eos",
          "body": "voluptates quo voluptatem facilis iure occaecati\nvel assumenda rerum officia et\nillum perspiciatis ab deleniti\nlaudantium repellat ad ut et autem reprehenderit"
     },
     {
          "userId": 5,
          "id": 49,
          "title": "laborum non sunt aut ut assumenda perspiciatis voluptas",
          "body": "inventore ab sint\nnatus fugit id nulla sequi architecto nihil quaerat\neos tenetur in in eum veritatis non\nquibusdam officiis aspernatur cumque aut commodi aut"
     },
     {
          "userId": 5,
          "id": 50,
          "title": "repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem",
          "body": "error suscipit maxime adipisci consequuntur recusandae\nvoluptas eligendi et est et voluptates\nquia distinctio ab amet quaerat molestiae et vitae\nadipisci impedit sequi nesciunt quis consectetur"
     },
     {
          "userId": 6,
          "id": 51,
          "title": "soluta aliquam aperiam consequatur illo quis voluptas",
          "body": "sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem"
     },
     {
          "userId": 6,
          "id": 52,
          "title": "qui enim et consequuntur quia animi quis voluptate quibusdam",
          "body": "iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum"
     },
     {
          "userId": 6,
          "id": 53,
          "title": "ut quo aut ducimus alias",
          "body": "minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique"
     },
     {
          "userId": 6,
          "id": 54,
          "title": "sit asperiores ipsam eveniet odio non quia",
          "body": "totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia"
     },
     {
          "userId": 6,
          "id": 55,
          "title": "sit vel voluptatem et non libero",
          "body": "debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit"
     },
     {
          "userId": 6,
          "id": 56,
          "title": "qui et at rerum necessitatibus",
          "body": "aut est omnis dolores\nneque rerum quod ea rerum velit pariatur beatae excepturi\net provident voluptas corrupti\ncorporis harum reprehenderit dolores eligendi"
     },
     {
          "userId": 6,
          "id": 57,
          "title": "sed ab est est",
          "body": "at pariatur consequuntur earum quidem\nquo est laudantium soluta voluptatem\nqui ullam et est\net cum voluptas voluptatum repellat est"
     },
     {
          "userId": 6,
          "id": 58,
          "title": "voluptatum itaque dolores nisi et quasi",
          "body": "veniam voluptatum quae adipisci id\net id quia eos ad et dolorem\naliquam quo nisi sunt eos impedit error\nad similique veniam"
     },
     {
          "userId": 6,
          "id": 59,
          "title": "qui commodi dolor at maiores et quis id accusantium",
          "body": "perspiciatis et quam ea autem temporibus non voluptatibus qui\nbeatae a earum officia nesciunt dolores suscipit voluptas et\nanimi doloribus cum rerum quas et magni\net hic ut ut commodi expedita sunt"
     },
     {
          "userId": 6,
          "id": 60,
          "title": "consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere",
          "body": "asperiores sunt ab assumenda cumque modi velit\nqui esse omnis\nvoluptate et fuga perferendis voluptas\nillo ratione amet aut et omnis"
     },
     {
          "userId": 7,
          "id": 61,
          "title": "voluptatem doloribus consectetur est ut ducimus",
          "body": "ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit"
     },
     {
          "userId": 7,
          "id": 62,
          "title": "beatae enim quia vel",
          "body": "enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio"
     },
     {
          "userId": 7,
          "id": 63,
          "title": "voluptas blanditiis repellendus animi ducimus error sapiente et suscipit",
          "body": "enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta"
     },
     {
          "userId": 7,
          "id": 64,
          "title": "et fugit quas eum in in aperiam quod",
          "body": "id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui"
     },
     {
          "userId": 7,
          "id": 65,
          "title": "consequatur id enim sunt et et",
          "body": "voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur"
     },
     {

In [16]:
h=data[:5]
#print(h)
for i in h:
    print(i["id"])
    print(i["title"])

1
sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2
qui est esse
3
ea molestias quasi exercitationem repellat qui ipsa sit aut
4
eum et est occaecati
5
nesciunt quas odio

In [17]:
for i in data[:5]:
    print(i["id"],"-",i["title"])

1 - sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2 - qui est esse
3 - ea molestias quasi exercitationem repellat qui ipsa sit aut
4 - eum et est occaecati
5 - nesciunt quas odio

In [22]:
url="https://jsonplaceholder.typicode.com/posts"
params={"userId":1}
response=requests.get(url,params=params)
print(response.status_code)
data=response.json()
#print(json.dumps(data,indent=5))
print(len(data))

200
10

In [23]:
response.url

'https://jsonplaceholder.typicode.com/posts?userId=1'

In [25]:
url="https://jsonplaceholder.typicode.com/posts/1"
header={'User-Agent':'Mozilla/5.0','Accept':'application/json'}
response=requests.get(url,headers=header)
print(response.status_code)
data=response.json()
print(json.dumps(data,indent=5))

200
{
     "userId": 1,
     "id": 1,
     "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
     "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

In [28]:
response.headers['Date']

'Sat, 30 May 2026 06:27:12 GMT'

In [34]:
url="https://jsonplaceholder.typicode.com/posts"
new_post={
    'title':"Learning Requests",
    "body":"This is tutorial",
    'userId':1
}
response=requests.post(url,json=new_post)
print(response.status_code)
print(response.json())

201
{'title': 'Learning Requests', 'body': 'This is tutorial', 'userId': 1, 'id': 101}

In [39]:
url="https://jsonplaceholder.typicode.com/posts/1"
new_post={
     "id":1,
    'title':"Updated Title",
    "body":"Updated Body",
    'userId':1
}
response=requests.put(url,json=new_post)
print(response.status_code)
print(response.json())

200
{'id': 1, 'title': 'Updated Title', 'body': 'Updated Body', 'userId': 1}

In [38]:
url="https://jsonplaceholder.typicode.com/posts/1"
new_post={
    'title':"Updated Title",
   }
response=requests.put(url,json=new_post)
print(response.status_code)
print(response.json())

200
{'title': 'Updated Title', 'id': 1}

In [41]:
url="https://jsonplaceholder.typicode.com/posts/1"
new_post={
    'title':"patched Title",
   }
response=requests.patch(url,json=new_post)
print(response.status_code)
print(response.json())

200
{'userId': 1, 'id': 1, 'title': 'patched Title', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [42]:
url="https://jsonplaceholder.typicode.com/posts/1"
response=requests.delete(url)
print(response.status_code)
print(response.json())

200
{}

In [45]:
url="https://picsum.photos/200"
response=requests.get(url)
with open('random_image.jpg','wb') as f:
   f.write(response.content)
print('image downloaded')

image downloaded

In [48]:
url="https://jsonplaceholder.typicode.com/posts/1"
response=requests.get(url)
data=response.json()
with open('post.json','w') as f:
   json.dump(data,f,indent=5)
print('file downloaded')

file downloaded

In [49]:
with open('post.json','r') as f:
    load_data=json.load(f)
print(load_data)

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [50]:
import pandas as pd
url="https://jsonplaceholder.typicode.com/posts"
response=requests.get(url)
data=response.json()
df=pd.DataFrame(data)
df

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

In [62]:
url="https://jsonplaceholder.typicode.com/users"
response=requests.get(url)
data=response.json()
print(f" Username:{data[0]['username']}")
print(f" Name:{data[0]['name']}")
print(f" Address:{data[0]['address']['city']}")
print(f" Username:{data[0]['address']['geo']['lat']}")
print(f" Username:{data[0]['address']['geo']['lng']}")
print(f" Username:{data[0]['email']}")
print(f" Username:{data[0]['company']['name']}")

 Username:Bret
 Name:Leanne Graham
 Address:Gwenborough
 Username:-37.3159
 Username:81.1496
 Username:Sincere@april.biz
 Username:Romaguera-Crona

In [75]:
Name=[]
Username=[]
Email=[]
Address=[]
Lat=[]
Lng=[]
Company_name=[]
for i in data:
    print(f"-----Data:{i['id']}-------")
    print(f" Username:{i['username']}")
    print(f" Name:{i['name']}")
    print(f" Address:{i['address']['city']}")
    print(f" lat:{i['address']['geo']['lat']}")
    print(f" Lng:{i['address']['geo']['lng']}")
    print(f" Email:{i['email']}")
    print(f" Company name:{i['company']['name']}")

-----Data:1-------
 Username:Bret
 Name:Leanne Graham
 Address:Gwenborough
 lat:-37.3159
 Lng:81.1496
 Email:Sincere@april.biz
 Company name:Romaguera-Crona
-----Data:2-------
 Username:Antonette
 Name:Ervin Howell
 Address:Wisokyburgh
 lat:-43.9509
 Lng:-34.4618
 Email:Shanna@melissa.tv
 Company name:Deckow-Crist
-----Data:3-------
 Username:Samantha
 Name:Clementine Bauch
 Address:McKenziehaven
 lat:-68.6102
 Lng:-47.0653
 Email:Nathan@yesenia.net
 Company name:Romaguera-Jacobson
-----Data:4-------
 Username:Karianne
 Name:Patricia Lebsack
 Address:South Elvis
 lat:29.4572
 Lng:-164.2990
 Email:Julianne.OConner@kory.org
 Company name:Robel-Corkery
-----Data:5-------
 Username:Kamren
 Name:Chelsey Dietrich
 Address:Roscoeview
 lat:-31.8129
 Lng:62.5342
 Email:Lucio_Hettinger@annie.ca
 Company name:Keebler LLC
-----Data:6-------
 Username:Leopoldo_Corkery
 Name:Mrs. Dennis Schulist
 Address:South Christy
 lat:-71.4197
 Lng:71.7478
 Email:Karley_Dach@jasper.info
 Company name:Considine-Lockman
-----Data:7-------
 Username:Elwyn.Skiles
 Name:Kurtis Weissnat
 Address:Howemouth
 lat:24.8918
 Lng:21.8984
 Email:Telly.Hoeger@billy.biz
 Company name:Johns Group
-----Data:8-------
 Username:Maxime_Nienow
 Name:Nicholas Runolfsdottir V
 Address:Aliyaview
 lat:-14.3990
 Lng:-120.7677
 Email:Sherwood@rosamond.me
 Company name:Abernathy Group
-----Data:9-------
 Username:Delphine
 Name:Glenna Reichert
 Address:Bartholomebury
 lat:24.6463
 Lng:-168.8889
 Email:Chaim_McDermott@dana.io
 Company name:Yost and Sons
-----Data:10-------
 Username:Moriah.Stanton
 Name:Clementina DuBuque
 Address:Lebsackbury
 lat:-38.2386
 Lng:57.2232
 Email:Rey.Padberg@karina.biz
 Company name:Hoeger LLC

In [ ]:
# for i in data:
#     Name.append(i['name'])
#     .append()

In [78]:
json_string='''{
"Name":"Alice",
"Age":25
}
'''
data=json.loads(json_string)
print(data)
print(type(json_string))
print(type(data))

{'Name': 'Alice', 'Age': 25}
<class 'str'>
<class 'dict'>

In [95]:
json_string={
"Name":"Alice",
"Age":25
}

data=json.dumps(json_string,indent=5)
print(data)
print(type(json_string))
print(type(data))

{
     "Name": "Alice",
     "Age": 25
}
<class 'dict'>
<class 'str'>

In [93]:
url="https://jsonplaceholder.typicode.com/posts"
params={
    '_page':2,
    '_limit':5
}
response=requests.get(url,params=params)
data=response.json()
for i in data:
    print(i['id']," -",i['title'])

6  - dolorem eum magni eos aperiam quia
7  - magnam facilis autem
8  - dolorem dolore est ipsam
9  - nesciunt iure omnis dolorem tempora et accusantium
10  - optio molestias id quia eum

In [92]:
url="https://jsonplaceholder.typicode.com/posts"
page=1
while page<=3:
    params={'_page':page,'_limit':5}
    response=requests.get(url,params=params)
    data=response.json()
    for i in data:
        print(i['id']," -",i['title'])
    page+=1

1  - sunt aut facere repellat provident occaecati excepturi optio reprehenderit
2  - qui est esse
3  - ea molestias quasi exercitationem repellat qui ipsa sit aut
4  - eum et est occaecati
5  - nesciunt quas odio
6  - dolorem eum magni eos aperiam quia
7  - magnam facilis autem
8  - dolorem dolore est ipsam
9  - nesciunt iure omnis dolorem tempora et accusantium
10  - optio molestias id quia eum
11  - et ea vero quia laudantium autem
12  - in quibusdam tempore odit est dolorem
13  - dolorum ut in voluptas mollitia et saepe quo animi
14  - voluptatem eligendi optio
15  - eveniet quod temporibus

In [96]:
import requests
url='https://jsonplaceholder.typicode.com/posts'
token='my_secret_token'
headers={'Authorization':f"Bearer{token}"}
response=requests.get(url,headers=headers)
print(response.status_code)
print(response.json())

200

In [3]:
import requests
response=requests.get('https://api.github.com/rate_limit')
data=response.json()
print(data)

print("limit: ",data['rate']['limit'])
print("Used: ",data['rate']['used'])
print("Remaining: ",data['rate']['remaining'])
print("Reset :",data['rate']['reset'])

{'resources': {'code_search': {'limit': 60, 'remaining': 57, 'reset': 1780288022, 'used': 3, 'resource': 'code_search'}, 'core': {'limit': 60, 'remaining': 57, 'reset': 1780288022, 'used': 3, 'resource': 'core'}, 'graphql': {'limit': 0, 'remaining': 0, 'reset': 1780288081, 'used': 0, 'resource': 'graphql'}, 'integration_manifest': {'limit': 5000, 'remaining': 5000, 'reset': 1780288081, 'used': 0, 'resource': 'integration_manifest'}, 'search': {'limit': 10, 'remaining': 10, 'reset': 1780284541, 'used': 0, 'resource': 'search'}}, 'rate': {'limit': 60, 'remaining': 57, 'reset': 1780288022, 'used': 3, 'resource': 'core'}}
limit:  60
Used:  3
Remaining:  57
Reset : 1780288022

In [10]:
for i in range(70):
    r=requests.get("https://api.github.com/users/octocat")
    print(i+1,r.status_code)
    if r.status_code==40:
        data.json()
        if "API rate limit exceeded"in data.get('message',""):
            print('rate limit exceeded')
            print(data['message'])
            break

1 403
2 403
3 403
4 403
5 403
6 403
7 403
8 403
9 403
10 403
11 403
12 403
13 403
14 403
15 403
16 403
17 403
18 403
19 403
20 403
21 403
22 403
23 403
24 403
25 403
26 403
27 403
28 403
29 403
30 403
31 403
32 403
33 403
34 403
35 403
36 403
37 403
38 403
39 403
40 403
41 403
42 403
43 403
44 403
45 403
46 403
47 403
48 403
49 403
50 403
51 403
52 403
53 403
54 403
55 403
56 403
57 403
58 403
59 403
60 403
61 403
62 403
63 403
64 403
65 403
66 403
67 403
68 403
69 403
70 403

In [9]:
from datetime import datetime
r=requests.get("https://api.github.com/rate_limit")
data=r.json()
reset_stamp=data['rate']['reset']
reset_time=datetime.fromtimestamp(reset_stamp).strftime("%y-%m-%d %H:%M:%S")
print(reset_time)

26-06-01 09:57:02